### ISSUE TITLE
IoT gig – Roughly 1 hour/day, 20 hours/month

### ISSUE THREAD

**Issue by Raytle** [Asocia/schoolwork#4]
Thanks for helping me with [How to randomly copy the contents of a text document to my clipboard](https://stackoverflow.com/questions/67126789/how-to-randomly-copy-the-contents-of-a-text-document-to-my-clipboard)

```
    import glob,random,pyperclip
    pattern = "/home/my_files/*.txt"
    path = random.choice(glob.glob(pattern))
    print("copying contents of ", path)
    The_text_of_the_file_that_will_be_copied = open(path, 'r').read()
    pyperclip.copy(The_text_of_the_file_that_will_be_copied)
```

Would you be interested in the following?

✻ OVERVIEW ✻
First, of course, we will need to agree on your hourly rate of pay.

I will pay you hourly with Bitcoin.

I estimate that you will normally work 1 hour/day.

I estimate that you will normally work 20 days/month.

If you are very intelligent and if you solve engineering problems scientifically then I will pay you to learn C/C++ on Arduino or MicroPython on ESP32. No. I am *not* being charitable. I am being practical. You must pass a difficult test to work with me.

You will help me build a consumer IoT (Internet of things) product.

✻ PAYING YOU TO LEARN ✻
No. You aren't dreaming.

I would rather work with an inexperienced person who is very intelligent and solves problems scientifically than an experienced person who is not very intelligent and/or does not solve problems scientifically.

✻ REMOTE DESKTOP SOFTWARE ✻
I have an extra computer which you will be able to remotely control when we work together. I suppose we will use Chrome Remote Desktop, or AnyDesk, or Nomachine. Therefore, you will be be able to program the Arduino or ESP32 connected to my extra computer.

✻ WORKING DAYS AND TIMES ✻
You and I will text chat (*not* video chat) and you will remotely control my extra computer for one hour on Sunday, Monday, Tuesday, Wednesday and Thursday during a time that is convenient for you and me.

✻ WHY ARDUINO OR ESP32? ✻
Frankly, I suppose if you were to actually experiment with MicroPython on ESP32 you would be pleasantly surprised that it would be much quicker and easier to use for this project. However, I presume every freelancer who has applied to work with me on this project has at least heard of C/C++ and Arduino. On the other hand even those applicants who have used the ESP32 have probably never even heard of MicroPython.

Therefore, understandably, many freelancers who apply to work with me on this project indicate they would prefer to use C/C++ on Arduino. At this point I’m primarily interested in recruiting the right candidate for this project. Therefore, if you were to pass this test and if you were to want to use C/C++ on Arduino I would allow you to work with me by using C/C++ on Arduino. But I suppose within a few months I would be able to persuade you that MicroPython on ESP32 would be better for this project.

**Comment by sahinakkaya** [comment]
Hmm, interesting...

Send me a message in [Telegram](t.me/sahinakkaya) so we can talk about the details.

**Comment by Raytle** [comment]
Sorry, I don't use Telegram. What if we correspond here?

**Comment by sahinakkaya** [comment]
I don't think it's good idea to discuss this in public. You can send me an email: sahin1akkaya@gmail.com
